mode: "dev"
port: 8081

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 101.34.184.109
  port: 3306
  user: root
  password: xiaoG11.
  db: bluebellv1
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 101.34.184.109
  port: 6379
  db: 0
  password: "xiaoG11."
  pool_size: 100